import {fields,parseProtocol,parseId,parseRevision} from './story-draft-validation.js';
import type {StoryProtocol} from './story-draft.js';
import {parseBudget} from './experience-opening-validation.js';
import {isTimestamp} from './primitives.js';
import {parseSceneResult,type SceneResult} from './generation-output.js';
export type HistoryQuery=StoryProtocol&{experienceId:string;limit?:number;beforeId?:string};
export type SavedSceneQuery=StoryProtocol&{experienceId:string;savepointId:string};
export type ForkCommand=SavedSceneQuery&{commandId:string;expectedSnapshotHash:string;branchBudgetLimitMicros:string;currency:'USD'|'CNY'};
export type ResumeForkCommand=StoryProtocol&{experienceId:string;commandId:string;expectedExperienceRevision:number};
export type SavedSceneDTO={id:string;sourceExperienceId:string;createdAt:string;snapshotHash:string;summary:string;inherited:boolean};
export type HistoryPage=StoryProtocol&{experienceId:string;items:SavedSceneDTO[];nextBeforeId:string|null};
export type SavedSceneDetail=StoryProtocol&{experienceId:string;savepoint:SavedSceneDTO;scene:SceneResult;media:{turnId:string;id:string;duration:number};canFork:boolean;budget:{limitMicros:string;currency:'USD'|'CNY'}};
export type ForkReceipt={data:StoryProtocol&{experienceId:string;rootExperienceId:string;sourceExperienceId:string;sourceSavepointId:string;initialSavepointId:string;initialInteractionEventId:string;budgetScopeId:string;acceptedAt:string};replayed:boolean};
const hash=(v:unknown)=>{if(typeof v!=='string'||!/^[a-f0-9]{64}$/.test(v))throw Error();return v;};
export function parseHistoryQuery(v:unknown):HistoryQuery&{limit:number}{try{fields(v,['protocolVersion','datasetId','experienceId'],['limit','beforeId']);const limit=v.limit??20;if(typeof limit!=='number'||!Number.isInteger(limit)||limit<1||limit>20)throw Error();return{...parseProtocol(v),experienceId:parseId(v.experienceId),limit,...(v.beforeId!==undefined?{beforeId:parseId(v.beforeId)}:{})};}catch{throw Error('INVALID_GENERATION_QUERY');}}
export function parseSavedSceneQuery(v:unknown):SavedSceneQuery{try{fields(v,['protocolVersion','datasetId','experienceId','savepointId']);return{...parseProtocol(v),experienceId:parseId(v.experienceId),savepointId:parseId(v.savepointId)};}catch{throw Error('INVALID_GENERATION_QUERY');}}
export function parseFork(v:unknown):ForkCommand{try{fields(v,['protocolVersion','datasetId','experienceId','savepointId','commandId','expectedSnapshotHash','branchBudgetLimitMicros','currency']);const b=parseBudget({limitMicros:v.branchBudgetLimitMicros,currency:v.currency});return{...parseProtocol(v),experienceId:parseId(v.experienceId),savepointId:parseId(v.savepointId),commandId:parseId(v.commandId),expectedSnapshotHash:hash(v.expectedSnapshotHash),branchBudgetLimitMicros:b.limitMicros,currency:b.currency};}catch{throw Error('INVALID_GENERATION_COMMAND');}}
export function parseResumeFork(v:unknown):ResumeForkCommand{try{fields(v,['protocolVersion','datasetId','experienceId','commandId','expectedExperienceRevision']);return{...parseProtocol(v),experienceId:parseId(v.experienceId),commandId:parseId(v.commandId),expectedExperienceRevision:parseRevision(v.expectedExperienceRevision)};}catch{throw Error('INVALID_GENERATION_COMMAND');}}
function saved(v:unknown):SavedSceneDTO{fields(v,['id','sourceExperienceId','createdAt','snapshotHash','summary','inherited']);if(!isTimestamp(v.createdAt)||typeof v.summary!=='string'||!v.summary||v.summary.length>2000||typeof v.inherited!=='boolean')throw Error();return{id:parseId(v.id),sourceExperienceId:parseId(v.sourceExperienceId),createdAt:v.createdAt,snapshotHash:hash(v.snapshotHash),summary:v.summary,inherited:v.inherited};}
export function parseHistoryPage(v:unknown):HistoryPage{try{fields(v,['protocolVersion','datasetId','experienceId','items','nextBeforeId']);if(!Array.isArray(v.items)||v.items.length>20)throw Error();const items=v.items.map(saved);for(let i=1;i<items.length;i++)if(items[i-1]!.id<=items[i]!.id)throw Error();return{...parseProtocol(v),experienceId:parseId(v.experienceId),items,nextBeforeId:v.nextBeforeId===null?null:parseId(v.nextBeforeId)};}catch{throw Error('INVALID_GENERATION_DTO');}}
export function parseSavedSceneDetail(v:unknown):SavedSceneDetail{try{fields(v,['protocolVersion','datasetId','experienceId','savepoint','scene','media','canFork','budget']);fields(v.media,['turnId','id','duration']);if(typeof v.canFork!=='boolean'||typeof v.media.duration!=='number'||v.media.duration<=0||v.media.duration>120)throw Error();return{...parseProtocol(v),experienceId:parseId(v.experienceId),savepoint:saved(v.savepoint),scene:parseSceneResult(v.scene),media:{turnId:parseId(v.media.turnId),id:parseId(v.media.id),duration:v.media.duration},canFork:v.canFork,budget:parseBudget(v.budget)};}catch{throw Error('INVALID_GENERATION_DTO');}}
export function parseForkReceipt(v:unknown):ForkReceipt{try{fields(v,['data','replayed']);fields(v.data,['protocolVersion','datasetId','experienceId','rootExperienceId','sourceExperienceId','sourceSavepointId','initialSavepointId','initialInteractionEventId','budgetScopeId','acceptedAt']);const d=v.data;if(typeof v.replayed!=='boolean'||!isTimestamp(d.acceptedAt))throw Error();return{data:{...parseProtocol(d),experienceId:parseId(d.experienceId),rootExperienceId:parseId(d.rootExperienceId),sourceExperienceId:parseId(d.sourceExperienceId),sourceSavepointId:parseId(d.sourceSavepointId),initialSavepointId:parseId(d.initialSavepointId),initialInteractionEventId:parseId(d.initialInteractionEventId),budgetScopeId:parseId(d.budgetScopeId),acceptedAt:d.acceptedAt},replayed:v.replayed};}catch{throw Error('INVALID_GENERATION_DTO');}}

export type RecoverForkQuery=StoryProtocol&{experienceId:string;commandId:string};
export function parseRecoverFork(v:unknown):RecoverForkQuery{try{fields(v,['protocolVersion','datasetId','experienceId','commandId']);return{...parseProtocol(v),experienceId:parseId(v.experienceId),commandId:parseId(v.commandId)};}catch{throw Error('INVALID_GENERATION_QUERY');}}
