export const OPENING_QUERY_MAX_BYTES = 8192;
export const OPENING_COMMAND_MAX_BYTES = 16384;
// Frozen story <=58,700 codepoints, three character copies <=54,360,
// two relationship copies <=8,000. Even 12-byte escaped astral codepoints
// plus fixed IDs/JSON structure fit 2 MiB; 128 bounded directory choices do too.
export const OPENING_RESPONSE_MAX_BYTES = 2 * 1024 * 1024;
export const OPENING_HTTP_STATUS = Object.freeze({
  INVALID_EXPERIENCE_COMMAND: 400, INVALID_EXPERIENCE_QUERY: 400,
  LOCAL_SESSION_INVALID: 401, LOCAL_ORIGIN_DENIED: 403,
  EXPERIENCE_NOT_FOUND: 404, STORY_NOT_FOUND: 404, PROVIDER_BINDING_NOT_REGISTERED: 404,
  REVISION_CONFLICT: 409, REVISION_EXHAUSTED: 409, IDEMPOTENCY_CONFLICT: 409,
  STORY_ARCHIVED: 409, STORY_ASSET_NOT_READY: 409, PROVIDER_BINDING_CONFLICT: 409, PREPARATION_NO_LONGER_CURRENT: 409,
  DATASET_CHANGED: 412, CLIENT_RELOAD_REQUIRED: 412, EXPERIENCE_REQUEST_TOO_LARGE: 413,
  EXPERIENCE_INTERNAL_ERROR: 500, PROVIDER_CONFIGURATION_UNAVAILABLE: 503, PROVIDER_NOT_INITIALIZED: 503,
} as const);
export type OpeningErrorCode = keyof typeof OPENING_HTTP_STATUS;
export function openingHTTPStatus(code: string): number | undefined {
  return Object.hasOwn(OPENING_HTTP_STATUS, code) ? OPENING_HTTP_STATUS[code as OpeningErrorCode] : undefined;
}
const codes = {400: 'BAD_REQUEST', 401: 'UNAUTHORIZED', 403: 'FORBIDDEN', 404: 'NOT_FOUND', 409: 'CONFLICT',
  412: 'PRECONDITION_FAILED', 413: 'PAYLOAD_TOO_LARGE', 500: 'INTERNAL_SERVER_ERROR', 503: 'SERVICE_UNAVAILABLE'} as const;
export function openingTRPCCode(status: number) {return codes[status as keyof typeof codes] ?? 'INTERNAL_SERVER_ERROR';}
