export const GENERATION_QUERY_MAX_BYTES = 8192;
export const GENERATION_COMMAND_MAX_BYTES = 16384;
// Four choices of <=2000 UTF-16 units plus summary, including JSON escaping.
export const GENERATION_RESPONSE_MAX_BYTES = 128 * 1024;
export const GENERATION_HTTP_STATUS = Object.freeze({
  INVALID_GENERATION_COMMAND: 400, INVALID_GENERATION_QUERY: 400,
  LOCAL_SESSION_INVALID: 401, LOCAL_ORIGIN_DENIED: 403, EXPERIENCE_NOT_FOUND: 404,
  REVISION_CONFLICT: 409, REVISION_EXHAUSTED: 409, IDEMPOTENCY_CONFLICT: 409,
  GENERATION_NOT_PLAYABLE: 409, GENERATION_CONTENT_UNCONFIRMED: 409,
  DATASET_CHANGED: 412, CLIENT_RELOAD_REQUIRED: 412, GENERATION_REQUEST_TOO_LARGE: 413,
  GENERATION_INTERNAL_ERROR: 500, STORE_AUTHORITY_UNAVAILABLE: 503,
} as const);
export type GenerationErrorCode = keyof typeof GENERATION_HTTP_STATUS;
export function generationHTTPStatus(code: string): number | undefined {
  return Object.hasOwn(GENERATION_HTTP_STATUS, code) ? GENERATION_HTTP_STATUS[code as GenerationErrorCode] : undefined;
}
const codes = {400: 'BAD_REQUEST', 401: 'UNAUTHORIZED', 403: 'FORBIDDEN', 404: 'NOT_FOUND', 409: 'CONFLICT',
  412: 'PRECONDITION_FAILED', 413: 'PAYLOAD_TOO_LARGE', 500: 'INTERNAL_SERVER_ERROR', 503: 'SERVICE_UNAVAILABLE'} as const;
export function generationTRPCCode(status: number) {return codes[status as keyof typeof codes] ?? 'INTERNAL_SERVER_ERROR';}
