import {describe,it,expect,vi} from 'vitest';
import {SessionController,buildOpeningPrompt} from './session-controller';
import type {LiveVideoProvider,VideoEvent,LiveVideoSession} from './types';
const options={prompt:'世界',aspectRatio:'9:16' as const,resolution:'480p' as const};
function fixture(){let emit!:(e:VideoEvent)=>void;const peer={send:vi.fn(),close:vi.fn(async()=>{})};const provider:LiveVideoProvider={id:'test',label:'test',capabilities:{audioOutput:true,voiceInput:false,cancelDirection:false},open:vi.fn(async(_,cb)=>{emit=cb;return peer;})};const c=new SessionController(provider);return{c,peer,provider,event:(e:VideoEvent)=>emit(e)};}
describe('real session lifecycle',()=>{
 it('never opens twice on repeated start',async()=>{const s=fixture();await Promise.all([s.c.start(options),s.c.start(options)]);expect(s.provider.open).toHaveBeenCalledTimes(1);await s.c.close();});
 it('blocks actions before configured, records sent/accepted/generated separately',async()=>{const s=fixture();await s.c.start(options);expect(()=>s.c.send('a','去窗边')).toThrow();s.event({type:'state',state:'ready'});s.c.send('a','去窗边');s.event({type:'intent',inputId:'a',state:'accepted'});expect(s.c.getSnapshot().intents[0].state).toBe('accepted');s.event({type:'intent',inputId:'a',state:'generated'});expect(s.c.getSnapshot().intents[0].state).toBe('generated');expect(s.c.getSnapshot().media).toBe('waiting');await s.c.close();});
 it('closes a late-opened peer before completing exit',async()=>{let resolve!:(s:LiveVideoSession)=>void;const peer={send:vi.fn(),close:vi.fn(async()=>{})};const p:LiveVideoProvider={id:'test',label:'test',capabilities:{audioOutput:false,voiceInput:false,cancelDirection:false},open:()=>new Promise(r=>{resolve=r;})};const c=new SessionController(p);const start=c.start(options);const closed=c.close();expect(c.getSnapshot().phase).toBe('ending');resolve(peer);await Promise.all([start,closed]);expect(peer.close).toHaveBeenCalledTimes(1);expect(c.getSnapshot().phase).toBe('ended');});
 it('retains rejected text and ignores regressive receipts',async()=>{const s=fixture();await s.c.start(options);s.event({type:'state',state:'ready'});s.c.send('a','原始表达');s.event({type:'intent',inputId:'a',state:'rejected'});s.event({type:'intent',inputId:'a',state:'accepted'});expect(s.c.getSnapshot().intents[0]).toMatchObject({text:'原始表达',state:'rejected'});await s.c.close();});
 it('does not erase failure when transport later reports closed',async()=>{const s=fixture();await s.c.start(options);s.event({type:'error',message:'连接失败'});s.event({type:'state',state:'closed'});expect(s.c.getSnapshot().phase).toBe('failed');expect(s.c.getSnapshot().error).toBe('连接失败');await s.c.close();});
 it('keeps close failures actionable and allows cleanup retry',async()=>{const s=fixture();await s.c.start(options);s.peer.close.mockRejectedValueOnce(Error('failed'));await expect(s.c.close()).rejects.toThrow();expect(s.c.getSnapshot().phase).toBe('failed');await s.c.close();expect(s.c.getSnapshot().phase).toBe('ended');});
 it('includes character boundaries and opening without forcing player choices',()=>{const prompt=buildOpeningPrompt({id:'x',title:'测试',world:'世界',opening:'开场',character:'甲',personality:'温和',genre:'日常',image:'sea',boundaries:'保持距离',relationship:'陌生人',speakingStyle:'简短',appearance:'短发'});for(const text of ['保持距离','陌生人','简短','短发','开场'])expect(prompt).toContain(text);});
});
