import {describe,it,expect,vi} from 'vitest';
import {StoryClientError} from './story-ports';
import {datasetId,otherDataset,rootId,assetId,version,draft,storyClient,deferred,settings} from './story-test-fixtures';
import type {DraftCommandResult} from '../../../runtime/src/contracts/story-draft';
async function setup(){const m=await import('./story-controller');const controller=new m.StoryController(),client=storyClient(),binding={client,connected:true,datasetId,invalidate:vi.fn()};controller.bind(binding);return{controller,client,binding};}
it('exports the original-story aggregate controller',async()=>{const m=await import('./story-controller').catch(()=>({StoryController:undefined}));expect(m.StoryController).toBeTypeOf('function');});
describe('story aggregate command state',()=>{
 it('preserves all settings, fixed version and relationship on read/update',async()=>{const{controller,client}=await setup();await controller.open(rootId);controller.field('world','新世界');await controller.save();expect(client.update.mock.calls[0]![0].patch).toMatchObject({settings:{...settings,world:'新世界'},mainCharacter:{kind:'bound',characterVersionId:version.id,overrides:{relationship:'旧友',portrait:{mode:'inherit'}}},assetSlots:draft().assetSlots});});
 it('locks before await and acknowledges A without replacing B or remounting editing instance',async()=>{const{controller,client}=await setup();controller.newDraft();controller.field('title','A');const pending=deferred<DraftCommandResult>();client.create.mockReturnValueOnce(pending.promise);const key=controller.getSnapshot().editingKey,first=controller.save();expect(controller.save()).toBe(first);controller.field('title','B');pending.resolve({data:draft({title:'A',mainCharacter:null,assetSlots:{cover:null,opening:null,character:null}}),replayed:false});await first;expect(client.create).toHaveBeenCalledTimes(1);expect(controller.getSnapshot()).toMatchObject({editingKey:key,fields:{title:'B'},confirmed:{id:rootId},dirty:true});await controller.save();expect(client.update.mock.calls[0]![0]).toMatchObject({id:rootId,expectedRevision:1,patch:{title:'B'}});});
 it.each(['create','update','delete','restore'] as const)('%s retains sticky unknown through 400 and protocol 412 until original receipt',async kind=>{const{controller,client}=await setup();if(kind==='create'){controller.newDraft();controller.field('title','A');}else await controller.open(rootId);const submit=()=>kind==='delete'||kind==='restore'?controller.lifecycle(kind):controller.save();client[kind].mockRejectedValueOnce(Error('lost'));await expect(submit()).rejects.toThrow();const input=structuredClone(client[kind].mock.calls[0]![0]);controller.field('world','B');for(const error of [new StoryClientError('INVALID_STORY_COMMAND',400,'rejected'),new StoryClientError('CLIENT_RELOAD_REQUIRED',412,'rejected')]){client[kind].mockRejectedValueOnce(error);await expect(controller.confirm()).rejects.toThrow();expect(controller.getSnapshot().unknown).toBe(true);}client[kind].mockResolvedValueOnce({data:draft(),replayed:true});await controller.confirm();expect(client[kind].mock.calls.map(([x])=>x)).toEqual([input,input,input,input]);expect(controller.getSnapshot()).toMatchObject({unknown:false,fields:{world:'B'}});});
 it('allows trusted first rejection to terminate but treats arbitrary 400 as unknown',async()=>{const{controller,client}=await setup();controller.newDraft();controller.field('title','A');client.create.mockRejectedValueOnce(new StoryClientError('INVALID_STORY_COMMAND',400,'rejected'));await expect(controller.save()).rejects.toThrow();expect(controller.getSnapshot().unknown).toBe(false);client.create.mockRejectedValueOnce({status:400});await expect(controller.save()).rejects.toBeTruthy();expect(controller.getSnapshot().unknown).toBe(true);});
 it('keeps same-dataset fenced write and never accepts its old response',async()=>{const{controller,client,binding}=await setup();controller.newDraft();controller.field('title','A');const late=deferred<DraftCommandResult>();client.create.mockReturnValueOnce(late.promise);const old=controller.save().catch(()=>{});controller.bind({...binding,invalidate:vi.fn()});client.create.mockRejectedValueOnce(new StoryClientError('INVALID_STORY_COMMAND',400,'rejected'));await expect(controller.confirm()).rejects.toThrow();late.resolve({data:draft(),replayed:false});await old;expect(controller.getSnapshot().unknown).toBe(true);await controller.confirm();expect(new Set(client.create.mock.calls.map(([x])=>x.commandId)).size).toBe(1);});
 it('cross-dataset recovery clears identities, source, all images, but retains every text field',async()=>{const{controller,client,binding}=await setup();await controller.open(rootId);const old=controller.getSnapshot().fields;controller.bind({...binding,datasetId:otherDataset});await expect(controller.save()).rejects.toThrow();expect(client.create).not.toHaveBeenCalled();controller.fromRetained();expect(controller.getSnapshot()).toMatchObject({confirmed:null,datasetChanged:false,fields:{world:old.world,playerRole:old.playerRole,worldRules:old.worldRules,relationship:old.relationship,source:null,portrait:{mode:'inherit'},assetSlots:{cover:null,opening:null,character:null}}});await controller.save();expect(client.create.mock.calls[0]![0]).toMatchObject({datasetId:otherDataset,mainCharacter:{kind:'inline',portraitAssetId:null}});});
 it('library selection freezes on acknowledgement and later text becomes bound overrides',async()=>{const{controller,client}=await setup();controller.newDraft();controller.field('title','A');controller.useCharacter({id:version.characterTemplateId,name:version.name,...version.settings,source:{kind:'formal-template',templateId:version.characterTemplateId,revision:3,datasetId,portraitAssetId:assetId},portraitRef:{kind:'formal',datasetId,id:assetId}});controller.field('relationship','同伴');await controller.save();expect(client.create.mock.calls[0]![0].mainCharacter).toMatchObject({kind:'library',expectedTemplateRevision:3,overrides:{relationship:'同伴',portrait:{mode:'inherit'}}});controller.field('personality','新覆盖');await controller.save();expect(client.update.mock.calls[0]![0].patch.mainCharacter).toMatchObject({kind:'bound',characterVersionId:version.id,overrides:{settings:{personality:'新覆盖'}}});});
 it('does not silently discard an unnamed inline character with draft text',async()=>{const{controller,client}=await setup();controller.newDraft();controller.field('title','A');controller.field('personality','尚未命名');await expect(controller.save()).rejects.toThrow();expect(client.create).not.toHaveBeenCalled();expect(controller.getSnapshot()).toMatchObject({fields:{personality:'尚未命名'},error:expect.stringContaining('角色姓名')});});
 it('keeps three slots consistent with portrait inherit/none/asset and scopes uploads',async()=>{const{controller,client}=await setup();await controller.open(rootId);const key=controller.getSnapshot().editingKey;expect(controller.selectAsset('opening',{kind:'formal',datasetId:otherDataset,id:assetId},key)).toBe(false);expect(controller.selectAsset('opening',{kind:'formal',datasetId,id:assetId},'old-key')).toBe(false);controller.selectAsset('opening',{kind:'formal',datasetId,id:assetId},key);controller.selectAsset('character',{kind:'formal',datasetId,id:assetId},key);await controller.save();expect(client.update.mock.calls[0]![0].patch).toMatchObject({assetSlots:{cover:assetId,opening:assetId,character:assetId},mainCharacter:{overrides:{portrait:{mode:'asset',assetId}}}});controller.portraitMode('none');expect(controller.getSnapshot().fields.assetSlots.character).toBeNull();controller.portraitMode('inherit');expect(controller.getSnapshot().fields.source).toMatchObject({kind:'bound',version:{portraitAssetId:assetId}});});
 it('separates list failure from empty and ignores stale reads across editing/dataset scopes',async()=>{const{controller,client,binding}=await setup();await controller.load();expect(controller.getSnapshot().listStatus).toBe('ready');client.list.mockRejectedValueOnce(Error('offline'));await controller.load();expect(controller.getSnapshot().listStatus).toBe('error');const late=deferred<ReturnType<typeof draft>>();client.get.mockReturnValueOnce(late.promise);const reading=controller.open(rootId);controller.bind({...binding,datasetId:otherDataset});late.resolve(draft());await reading;expect(controller.getSnapshot().confirmed).toBeNull();expect(controller.getSnapshot().reading).toBe(false);});
 it('sends title query, exact genre, cursor and totalMatching without local broad search',async()=>{const{controller,client}=await setup();client.list.mockResolvedValue({protocolVersion:1,datasetId,items:[],nextCursor:'next',totalMatching:17});await controller.load({q:'标题%',genre:'奇幻'});await controller.load(undefined,true);expect(client.list.mock.calls[1]![0]).toMatchObject({protocolVersion:1,datasetId,q:'标题%',genre:'奇幻',cursor:'next'});expect(controller.getSnapshot().total).toBe(17);});
});
it('a first trusted protocol rejection may finish, without auto refresh or discarding text',async()=>{const{controller,client}=await setup();controller.newDraft();controller.field('title','A');client.create.mockRejectedValueOnce(new StoryClientError('CLIENT_RELOAD_REQUIRED',412,'rejected'));await expect(controller.save()).rejects.toThrow();expect(controller.getSnapshot()).toMatchObject({unknown:false,fields:{title:'A'},error:expect.stringContaining('不会自动刷新')});});
