import {v7,validate,version as uuidVersion} from 'uuid';
import type {DraftCreate,DraftUpdate,DraftLifecycle,DraftDTO,DraftSummaryDTO} from '../../../runtime/src/contracts/story-draft';
import type {StoryDraftClient} from './story-ports';
import type {AssetRef} from './asset-ports';
import type {CharacterSelection} from './character-viewmodel';
import {emptyStoryFields,storyFields,storyFingerprint,storyPayload,storyFailure,withCharacter,type StoryFields} from './story-viewmodel';
type Command={kind:'create';input:DraftCreate}|{kind:'update';input:DraftUpdate}|{kind:'delete'|'restore';input:DraftLifecycle};
type Binding={client:StoryDraftClient;connected:boolean;datasetId:string|null;invalidate:()=>void};
type Filters={q:string;genre?:string;deleted:'exclude'|'only'};
export type StoryState={assetDatasetId:string|null;fields:StoryFields;confirmed:DraftDTO|null;editingKey:string;editing:boolean;connected:boolean;dirty:boolean;unknown:boolean;datasetChanged:boolean;saving:boolean;reading:boolean;items:DraftSummaryDTO[];cursor:string|null;total:number;filters:Filters;listBusy:boolean;listStatus:'idle'|'ready'|'error';error:string;listError:string;message:string};
export class StoryController{
 private state:StoryState={assetDatasetId:null,fields:emptyStoryFields(),confirmed:null,editingKey:v7(),editing:false,connected:false,dirty:false,unknown:false,datasetChanged:false,saving:false,reading:false,items:[],cursor:null,total:0,filters:{q:'',deleted:'exclude'},listBusy:false,listStatus:'idle',error:'',listError:'',message:''};
 private binding:Binding|null=null;private epoch=0;private readSequence=0;private listSequence=0;private listeners=new Set<()=>void>();private pending:Command|null=null;private flight:Promise<DraftDTO>|null=null;private baseline=storyFingerprint(this.state.fields);
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};getSnapshot=()=>this.state;get datasetId(){return this.binding?.datasetId??null;}
 private publish(patch:Partial<StoryState>){this.state={...this.state,...patch};this.state.dirty=this.state.unknown||this.state.datasetChanged||(this.state.editing&&storyFingerprint(this.state.fields)!==this.baseline);this.listeners.forEach(fn=>fn());}
 private fence(){this.epoch++;this.readSequence++;this.listSequence++;this.flight=null;this.publish({saving:false,reading:false,listBusy:false,...(this.pending?{unknown:true}:{})});}
 bind(next:Binding){const old=this.binding;if(old&&old.client===next.client&&old.connected===next.connected&&old.datasetId===next.datasetId&&old.invalidate===next.invalidate)return;this.fence();this.binding=next;const changed=Boolean(old?.datasetId&&next.datasetId&&old.datasetId!==next.datasetId);this.publish({connected:next.connected,...(changed?{datasetChanged:Boolean(this.pending||this.state.editing),confirmed:null,items:[],cursor:null,total:0,listStatus:'idle' as const}:{})});}
 suspend(){this.fence();}
 private writable(){return Boolean(this.binding?.connected&&this.state.connected&&!this.state.datasetChanged);}
 private reset(){this.fence();this.publish({connected:false,datasetChanged:Boolean(this.pending||this.state.editing),confirmed:null,items:[],cursor:null,total:0,listStatus:'idle'});}
 newDraft(){if(this.state.saving||this.state.unknown||this.state.datasetChanged)return false;this.readSequence++;this.pending=null;const fields=emptyStoryFields();this.baseline=storyFingerprint(fields);this.publish({assetDatasetId:this.datasetId,fields,confirmed:null,editing:true,editingKey:v7(),reading:false,error:'',message:''});return true;}
 close(){if(this.state.saving||this.state.unknown||this.state.datasetChanged)return false;this.readSequence++;this.publish({editing:false,reading:false});return true;}
 field<K extends keyof Pick<StoryFields,'title'|'world'|'opening'|'genre'|'playerRole'|'tone'|'worldRules'|'character'|'personality'|'appearance'|'speakingStyle'|'boundaries'|'relationship'>>(key:K,value:StoryFields[K]){this.readSequence++;this.publish({fields:{...this.state.fields,[key]:value},reading:false,message:''});}
 useCharacter(c:CharacterSelection){if(!this.writable()||this.state.saving||this.state.unknown||c.source?.datasetId!==this.datasetId)return false;this.publish({assetDatasetId:this.datasetId,fields:withCharacter(this.state.fields,c)});return true;}
 clearCharacter(){if(this.state.saving||this.state.unknown||this.state.datasetChanged)return;const blank=emptyStoryFields();this.publish({fields:{...this.state.fields,character:'',personality:'',appearance:'',speakingStyle:'',boundaries:'',relationship:'',source:null,portrait:blank.portrait,assetSlots:{...this.state.fields.assetSlots,character:null}}});}
 portraitMode(mode:'inherit'|'none'){if(this.state.saving||this.state.unknown||this.state.datasetChanged)return;this.publish({fields:{...this.state.fields,portrait:{mode},assetSlots:{...this.state.fields.assetSlots,character:null}}});}
 selectAsset(role:'cover'|'opening'|'character',ref:AssetRef|null,editingKey:string){if(!this.writable()||this.state.saving||this.state.unknown||editingKey!==this.state.editingKey||(ref&&(ref.kind!=='formal'||ref.datasetId!==this.datasetId||!validate(ref.id)||uuidVersion(ref.id)!==7)))return false;this.publish({assetDatasetId:this.datasetId,fields:{...this.state.fields,assetSlots:{...this.state.fields.assetSlots,[role]:ref?.id??null},...(role==='character'?{portrait:ref?{mode:'asset' as const,assetId:ref.id}:{mode:'none' as const}}:{})}});return true;}
 fromRetained(){if(!this.state.connected||this.state.saving||!this.state.datasetChanged)return false;this.pending=null;this.readSequence++;const fields={...this.state.fields,source:null,portrait:{mode:'inherit' as const},assetSlots:{cover:null,opening:null,character:null},assetViews:[]};this.baseline=storyFingerprint(emptyStoryFields());this.publish({assetDatasetId:this.datasetId,fields,confirmed:null,unknown:false,datasetChanged:false,editing:true,editingKey:v7(),error:'',message:''});return true;}
 async load(filters:Partial<Filters>=this.state.filters,append=false){const b=this.binding;if(!this.writable()||!b?.datasetId)return;const query={...this.state.filters,...filters},epoch=this.epoch,seq=++this.listSequence,current=()=>epoch===this.epoch&&seq===this.listSequence;this.publish({listBusy:true,listError:'',filters:query});try{const page=await b.client.list({protocolVersion:1,datasetId:b.datasetId,...query,limit:20,...(append&&this.state.cursor?{cursor:this.state.cursor}:{})});if(!current())return;this.publish({items:[...new Map((append?[...this.state.items,...page.items]:page.items).map(x=>[x.id,x])).values()],cursor:page.nextCursor,total:page.totalMatching,listStatus:'ready'});}catch(error){if(current()){const info=storyFailure(error);this.publish({listStatus:'error',listError:'剧本列表读取失败；已读取内容仍保留，请重试。'});if(info.reset)this.reset();if(info.denied||info.reset)b.invalidate();}}finally{if(current())this.publish({listBusy:false});}}
 async open(id:string,editing=true){const b=this.binding;if(!this.writable()||!b?.datasetId||this.state.saving||this.state.unknown)return false;const epoch=this.epoch,seq=++this.readSequence,current=()=>epoch===this.epoch&&seq===this.readSequence;this.publish({reading:true,error:''});try{const dto=await b.client.get({protocolVersion:1,datasetId:b.datasetId,id,includeDeleted:true});if(!current())return false;const fields=storyFields(dto);this.baseline=storyFingerprint(fields);this.publish({assetDatasetId:dto.datasetId,fields,confirmed:dto,editing,editingKey:v7(),message:''});return true;}catch(error){if(current()){const info=storyFailure(error);this.publish({error:info.message});if(info.reset)this.reset();if(info.denied||info.reset)b.invalidate();}return false;}finally{if(current())this.publish({reading:false});}}
 save():Promise<DraftDTO>{if(this.flight)return this.flight;if(this.state.unknown)return this.confirm();if(!this.writable()||!this.datasetId)return Promise.reject(Error('请先连接当前数据集；重置后须显式新建。'));if(this.state.confirmed?.deletedAt)return Promise.reject(Error('请先恢复剧本。'));try{const payload=storyPayload(this.state.fields),base={protocolVersion:1 as const,datasetId:this.datasetId,commandId:v7()},dto=this.state.confirmed;if(!dto&&payload.mainCharacter?.kind==='bound')throw Error('固定角色只能保留在原剧本，请从保留文本新建。');return this.execute(dto?{kind:'update',input:{...base,id:dto.id,expectedRevision:dto.revision,patch:payload}}:{kind:'create',input:{...base,...payload,mainCharacter:payload.mainCharacter as DraftCreate['mainCharacter']}});}catch(error){this.publish({error:error instanceof Error?error.message:'请检查剧本字段。'});return Promise.reject(error);}}
 confirm():Promise<DraftDTO>{if(this.flight)return this.flight;if(!this.pending||!this.writable())return Promise.reject(Error('原剧本命令暂不可确认。'));return this.execute(this.pending);}
 lifecycle(kind:'delete'|'restore'):Promise<DraftDTO>{if(this.flight)return this.flight;const dto=this.state.confirmed;if(!dto||!this.writable()||this.state.unknown)return Promise.reject(Error('当前剧本暂不可修改。'));return this.execute({kind,input:{protocolVersion:1,datasetId:this.datasetId!,commandId:v7(),id:dto.id,expectedRevision:dto.revision}});}
 private execute(command:Command):Promise<DraftDTO>{const b=this.binding!;if(command.input.datasetId!==b.datasetId){this.reset();return Promise.reject(Error('DATASET_CHANGED'));}const epoch=this.epoch,fields=structuredClone(this.state.fields),current=()=>epoch===this.epoch&&this.pending===command;let done!:(value:DraftDTO)=>void,fail!:(error:unknown)=>void;const task=new Promise<DraftDTO>((yes,no)=>{done=yes;fail=no;});this.flight=task;this.pending=command;this.publish({saving:true,error:'',message:''});void(async()=>{try{const result=command.kind==='create'?await b.client.create(command.input):command.kind==='update'?await b.client.update(command.input):await b.client[command.kind](command.input);if(!current())throw Error('STORY_RESPONSE_SUPERSEDED');const dto=result.data,ack=storyFields(dto),working=this.state.fields;
 // Only binding identity changes after acknowledgement; working text/assets B are never replaced.
 const acknowledgedFields={...working,source:JSON.stringify(working.source)===JSON.stringify(fields.source)?ack.source:working.source,assetViews:ack.assetViews};
 this.baseline=storyFingerprint(ack);this.pending=null;this.publish({fields:acknowledgedFields,confirmed:dto,unknown:false,saving:false,message:result.replayed?'原剧本命令已确认；后续修改仍需保存。':'剧本与图片已保存到本机。'});void this.load();return dto;
 }catch(error){if(current()){const info=storyFailure(error),unknown=this.state.unknown||info.reset||!info.definitive;if(!unknown)this.pending=null;this.publish({unknown,error:info.message,saving:false});if(info.reset)this.reset();if(info.denied||info.reset)b.invalidate();}throw error;}finally{if(epoch===this.epoch){this.flight=null;this.publish({saving:false});}}})().then(done,fail);return task;}
}
