import {afterEach, beforeEach, expect, it} from 'vitest';
import {mkdtemp, realpath, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {v7} from 'uuid';
import * as host from '../src/host/index.js';
let parent: string;
beforeEach(async () => {parent = await mkdtemp(join(await realpath(tmpdir()), 'local-characters-'));});
afterEach(async () => {await rm(parent, {recursive: true, force: true});});
it('provides independent six-operation character composition on a temporary authenticated host', async () => {
  expect(typeof (host as Record<string, unknown>).withLocalCharacters).toBe('function');
  const directory = join(parent, 'host'), manifest = await host.initializeLocalHost(directory, 'dev');
  const session = await host.exchangeConnectionCode(directory, 'dev', await host.issueConnectionCode(directory, 'dev'));
  const withCharacters = host.withLocalCharacters;
  const command = {datasetId: manifest.datasetId, commandId: v7(), name: '正式角色', settings: {personality: '', appearance: '', speakingStyle: '', boundaries: ''}, portraitAssetId: null};
  const work = <T>(fn: Parameters<typeof withCharacters<T>>[3]) => withCharacters(directory, 'dev', session.token, fn);
  const created = await work((s, o) => s.create(o, command));
  expect(await work((s, o) => s.get(o, created.data.id))).toEqual(created.data);
  expect((await work((s, o) => s.list(o))).totalMatching).toBe(1);
  const life = (expectedRevision: number) => ({datasetId: manifest.datasetId, commandId: v7(), id: created.data.id, expectedRevision});
  await work((s, o) => s.update(o, {...life(1), patch: {name: '已更新'}}));
  await work((s, o) => s.delete(o, life(2)));
  expect((await work((s, o) => s.list(o))).totalMatching).toBe(0);
  await work((s, o) => s.restore(o, life(3)));
  const reconnected = await host.exchangeConnectionCode(directory, 'dev', await host.issueConnectionCode(directory, 'dev'));
  expect(await withCharacters(directory, 'dev', reconnected.token, (s, o) => s.create(o, command))).toEqual({...created, replayed: true});
  expect((await host.withLocalStories(directory, 'dev', session.token, (s, o) => s.list(o, {protocolVersion: 1, datasetId: o.datasetId}))).items).toEqual([]);
  await expect(work((s, o) => s.create(o, {...command, datasetId: v7()}))).rejects.toThrow('DATASET_CHANGED');
  await expect(work((s, o) => s.create(o, {...command, commandId: v7(), portraitAssetId: v7()}))).rejects.toThrow('INVALID_CHARACTER_PORTRAIT');
  await expect(work(async () => {throw Error('SQL /private/path');})).rejects.toThrow('LOCAL_CHARACTERS_FAILED');
  await host.revokeSession(directory, 'dev', session.token);
  let called = false; await expect(work(async () => {called = true;})).rejects.toThrow('LOCAL_SESSION_INVALID'); expect(called).toBe(false);
}, 30_000);
