// Generated from reviewed migration-chain SQL, never from a user database.
// Exact sqlite_master DDL fingerprints cover names, columns, defaults, constraints,
// index column order/uniqueness/expressions and table options. No legacy allowlist.
export const approvedMigrations = [
  {
    "name": "202609120001_authoring_baseline",
    "checksum": "22f92a219d81d743476fd3c60ba15a9d98c05c8d224599565e407b5db3854c94"
  },
  {
    "name": "202609130001_execution_profiles",
    "checksum": "903f189463f0a7d2723f6a0205b1ffdcab98563d03570185f047a39ec1d1d5da"
  }
] as const;
export const approvedSchemaObjects = [
  {"type":"index","name":"ix_asset_uploads_asset","tableName":"asset_uploads","sql":"CREATE INDEX \"ix_asset_uploads_asset\" ON \"asset_uploads\"(\"asset_id\")"},
  {"type":"index","name":"ix_asset_uploads_owner","tableName":"asset_uploads","sql":"CREATE INDEX \"ix_asset_uploads_owner\" ON \"asset_uploads\"(\"owner_id\", \"created_at\", \"id\")"},
  {"type":"index","name":"ix_asset_uploads_recovery","tableName":"asset_uploads","sql":"CREATE INDEX \"ix_asset_uploads_recovery\" ON \"asset_uploads\"(\"status\", \"lease_expires_at\", \"id\")"},
  {"type":"index","name":"ix_assets_owner_hash","tableName":"assets","sql":"CREATE INDEX \"ix_assets_owner_hash\" ON \"assets\"(\"owner_id\", \"sha256\")"},
  {"type":"index","name":"ix_character_templates_portrait","tableName":"character_templates","sql":"CREATE INDEX \"ix_character_templates_portrait\" ON \"character_templates\"(\"owner_id\", \"portrait_asset_id\")"},
  {"type":"index","name":"ix_character_templates_scope_list","tableName":"character_templates","sql":"CREATE INDEX \"ix_character_templates_scope_list\" ON \"character_templates\"(\"owner_id\", \"scope\", \"deleted_at\", \"updated_at\", \"id\")"},
  {"type":"index","name":"ix_character_templates_story","tableName":"character_templates","sql":"CREATE INDEX \"ix_character_templates_story\" ON \"character_templates\"(\"owner_id\", \"source_story_draft_id\")"},
  {"type":"index","name":"ix_character_versions_portrait","tableName":"character_versions","sql":"CREATE INDEX \"ix_character_versions_portrait\" ON \"character_versions\"(\"owner_id\", \"portrait_asset_id\")"},
  {"type":"index","name":"ix_experiences_binding","tableName":"experiences","sql":"CREATE INDEX \"ix_experiences_binding\" ON \"experiences\"(\"owner_id\", \"provider_binding_version_id\")"},
  {"type":"index","name":"ix_experiences_owner_list","tableName":"experiences","sql":"CREATE INDEX \"ix_experiences_owner_list\" ON \"experiences\"(\"owner_id\", \"deleted_at\", \"archived_at\", \"updated_at\", \"id\")"},
  {"type":"index","name":"ix_experiences_story_version","tableName":"experiences","sql":"CREATE INDEX \"ix_experiences_story_version\" ON \"experiences\"(\"owner_id\", \"story_version_id\")"},
  {"type":"index","name":"ix_story_draft_assets_asset","tableName":"story_draft_assets","sql":"CREATE INDEX \"ix_story_draft_assets_asset\" ON \"story_draft_assets\"(\"owner_id\", \"asset_id\")"},
  {"type":"index","name":"ix_story_draft_cast_character","tableName":"story_draft_cast","sql":"CREATE INDEX \"ix_story_draft_cast_character\" ON \"story_draft_cast\"(\"owner_id\", \"character_version_id\")"},
  {"type":"index","name":"ix_story_drafts_owner_list","tableName":"story_drafts","sql":"CREATE INDEX \"ix_story_drafts_owner_list\" ON \"story_drafts\"(\"owner_id\", \"deleted_at\", \"archived_at\", \"updated_at\", \"id\")"},
  {"type":"index","name":"ix_story_version_assets_asset","tableName":"story_version_assets","sql":"CREATE INDEX \"ix_story_version_assets_asset\" ON \"story_version_assets\"(\"owner_id\", \"asset_id\")"},
  {"type":"index","name":"ix_story_version_cast_character","tableName":"story_version_cast","sql":"CREATE INDEX \"ix_story_version_cast_character\" ON \"story_version_cast\"(\"owner_id\", \"character_version_id\")"},
  {"type":"index","name":"uq_assets_storage_key","tableName":"assets","sql":"CREATE UNIQUE INDEX \"uq_assets_storage_key\" ON \"assets\"(\"storage_key\")"},
  {"type":"index","name":"uq_character_versions_number","tableName":"character_versions","sql":"CREATE UNIQUE INDEX \"uq_character_versions_number\" ON \"character_versions\"(\"character_template_id\", \"version_no\")"},
  {"type":"index","name":"uq_character_versions_source","tableName":"character_versions","sql":"CREATE UNIQUE INDEX \"uq_character_versions_source\" ON \"character_versions\"(\"character_template_id\", \"source_revision\")"},
  {"type":"index","name":"uq_command_receipts_owner_command","tableName":"command_receipts","sql":"CREATE UNIQUE INDEX \"uq_command_receipts_owner_command\" ON \"command_receipts\"(\"owner_id\", \"command_id\")"},
  {"type":"index","name":"uq_execution_profiles_version","tableName":"execution_profile_versions","sql":"CREATE UNIQUE INDEX \"uq_execution_profiles_version\" ON \"execution_profile_versions\"(\"owner_id\", \"profile_key\", \"version_no\")"},
  {"type":"index","name":"uq_interaction_events_revision","tableName":"interaction_events","sql":"CREATE UNIQUE INDEX \"uq_interaction_events_revision\" ON \"interaction_events\"(\"experience_id\", \"experience_revision\")"},
  {"type":"index","name":"uq_provider_binding_versions_number","tableName":"provider_binding_versions","sql":"CREATE UNIQUE INDEX \"uq_provider_binding_versions_number\" ON \"provider_binding_versions\"(\"owner_id\", \"binding_key\", \"version_no\")"},
  {"type":"index","name":"uq_response_drafts_node","tableName":"response_drafts","sql":"CREATE UNIQUE INDEX \"uq_response_drafts_node\" ON \"response_drafts\"(\"owner_id\", \"interaction_event_id\")"},
  {"type":"index","name":"uq_story_draft_assets_slot","tableName":"story_draft_assets","sql":"CREATE UNIQUE INDEX \"uq_story_draft_assets_slot\" ON \"story_draft_assets\"(\"story_draft_id\", \"slot_key\")"},
  {"type":"index","name":"uq_story_draft_cast_slot","tableName":"story_draft_cast","sql":"CREATE UNIQUE INDEX \"uq_story_draft_cast_slot\" ON \"story_draft_cast\"(\"story_draft_id\", \"slot_key\")"},
  {"type":"index","name":"uq_story_version_assets_slot","tableName":"story_version_assets","sql":"CREATE UNIQUE INDEX \"uq_story_version_assets_slot\" ON \"story_version_assets\"(\"story_version_id\", \"slot_key\")"},
  {"type":"index","name":"uq_story_version_cast_slot","tableName":"story_version_cast","sql":"CREATE UNIQUE INDEX \"uq_story_version_cast_slot\" ON \"story_version_cast\"(\"story_version_id\", \"slot_key\")"},
  {"type":"index","name":"uq_story_versions_number","tableName":"story_versions","sql":"CREATE UNIQUE INDEX \"uq_story_versions_number\" ON \"story_versions\"(\"story_draft_id\", \"version_no\")"},
  {"type":"index","name":"uq_story_versions_source","tableName":"story_versions","sql":"CREATE UNIQUE INDEX \"uq_story_versions_source\" ON \"story_versions\"(\"story_draft_id\", \"source_revision\")"},
  {"type":"table","name":"asset_uploads","tableName":"asset_uploads","sql":"CREATE TABLE \"asset_uploads\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"asset_id\" TEXT NOT NULL,\n    \"input_sha256\" TEXT NOT NULL,\n    \"input_byte_size\" BIGINT NOT NULL,\n    \"original_name\" TEXT NOT NULL,\n    \"rights_declaration\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL,\n    \"output_sha256\" TEXT,\n    \"output_byte_size\" BIGINT,\n    \"output_width\" INTEGER,\n    \"output_height\" INTEGER,\n    \"processing_token\" TEXT,\n    \"lease_expires_at\" DATETIME,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"expires_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"assets","tableName":"assets","sql":"CREATE TABLE \"assets\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"storage_key\" TEXT NOT NULL,\n    \"sha256\" TEXT NOT NULL,\n    \"mime_type\" TEXT NOT NULL,\n    \"byte_size\" BIGINT NOT NULL,\n    \"original_name\" TEXT NOT NULL,\n    \"width\" INTEGER NOT NULL,\n    \"height\" INTEGER NOT NULL,\n    \"rights_declaration\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL DEFAULT 'ready',\n    \"deleted_at\" DATETIME,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"character_templates","tableName":"character_templates","sql":"CREATE TABLE \"character_templates\" (\n    \"scope\" TEXT NOT NULL DEFAULT 'library',\n    \"source_story_draft_id\" TEXT,\n    \"deleted_at\" DATETIME,\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"settings\" JSONB NOT NULL,\n    \"portrait_asset_id\" TEXT,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"archived_at\" DATETIME,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"character_versions","tableName":"character_versions","sql":"CREATE TABLE \"character_versions\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"character_template_id\" TEXT NOT NULL,\n    \"version_no\" INTEGER NOT NULL,\n    \"source_revision\" INTEGER NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"settings\" JSONB NOT NULL,\n    \"portrait_asset_id\" TEXT,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"command_receipts","tableName":"command_receipts","sql":"CREATE TABLE \"command_receipts\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"command_id\" TEXT NOT NULL,\n    \"command_type\" TEXT NOT NULL,\n    \"payload_hash\" TEXT NOT NULL,\n    \"response\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"execution_profile_versions","tableName":"execution_profile_versions","sql":"CREATE TABLE \"execution_profile_versions\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"profile_key\" TEXT NOT NULL,\n    \"version_no\" INTEGER NOT NULL,\n    \"planner_binding_version_id\" TEXT NOT NULL,\n    \"video_binding_version_id\" TEXT NOT NULL,\n    \"validator_binding_version_id\" TEXT NOT NULL,\n    \"snapshot\" JSONB NOT NULL,\n    \"content_hash\" TEXT NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"experiences","tableName":"experiences","sql":"CREATE TABLE \"experiences\" (\n    \"budget_limit_micros\" BIGINT NOT NULL,\n    \"budget_currency\" TEXT NOT NULL,\n    \"deleted_at\" DATETIME,\n    \"row_revision\" INTEGER NOT NULL DEFAULT 1,\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_version_id\" TEXT NOT NULL,\n    \"provider_binding_version_id\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL DEFAULT 'preparing',\n    \"scheduling_paused\" BOOLEAN NOT NULL DEFAULT true,\n    \"dispatch_epoch\" INTEGER NOT NULL DEFAULT 0,\n    \"archived_at\" DATETIME,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"interaction_events","tableName":"interaction_events","sql":"CREATE TABLE \"interaction_events\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"experience_id\" TEXT NOT NULL,\n    \"kind\" TEXT NOT NULL,\n    \"experience_revision\" INTEGER NOT NULL,\n    \"options\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"local_profiles","tableName":"local_profiles","sql":"CREATE TABLE \"local_profiles\" (\n    \"write_epoch\" INTEGER NOT NULL DEFAULT 0,\n    \"deleted_at\" DATETIME,\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"display_name\" TEXT NOT NULL,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"provider_binding_versions","tableName":"provider_binding_versions","sql":"CREATE TABLE \"provider_binding_versions\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"binding_key\" TEXT NOT NULL,\n    \"version_no\" INTEGER NOT NULL,\n    \"provider_id\" TEXT NOT NULL,\n    \"model_id\" TEXT NOT NULL,\n    \"adapter_version\" TEXT NOT NULL,\n    \"capability_version\" TEXT NOT NULL,\n    \"mode\" TEXT NOT NULL,\n    \"credential_ref\" TEXT NOT NULL,\n    \"parameters\" JSONB NOT NULL,\n    \"capabilities\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"response_drafts","tableName":"response_drafts","sql":"CREATE TABLE \"response_drafts\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"experience_id\" TEXT NOT NULL,\n    \"interaction_event_id\" TEXT NOT NULL,\n    \"text\" TEXT NOT NULL DEFAULT '',\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"story_draft_assets","tableName":"story_draft_assets","sql":"CREATE TABLE \"story_draft_assets\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_draft_id\" TEXT NOT NULL,\n    \"asset_id\" TEXT NOT NULL,\n    \"slot_key\" TEXT NOT NULL,\n    \"purpose\" TEXT NOT NULL,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"story_draft_cast","tableName":"story_draft_cast","sql":"CREATE TABLE \"story_draft_cast\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_draft_id\" TEXT NOT NULL,\n    \"character_version_id\" TEXT NOT NULL,\n    \"slot_key\" TEXT NOT NULL,\n    \"overrides\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"story_drafts","tableName":"story_drafts","sql":"CREATE TABLE \"story_drafts\" (\n    \"deleted_at\" DATETIME,\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"settings\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"archived_at\" DATETIME,\n    \"created_at\" DATETIME NOT NULL,\n    \"updated_at\" DATETIME NOT NULL,\n    \"revision\" INTEGER NOT NULL DEFAULT 1\n)"},
  {"type":"table","name":"story_version_assets","tableName":"story_version_assets","sql":"CREATE TABLE \"story_version_assets\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_version_id\" TEXT NOT NULL,\n    \"asset_id\" TEXT NOT NULL,\n    \"slot_key\" TEXT NOT NULL,\n    \"purpose\" TEXT NOT NULL,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"story_version_cast","tableName":"story_version_cast","sql":"CREATE TABLE \"story_version_cast\" (\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_version_id\" TEXT NOT NULL,\n    \"character_version_id\" TEXT NOT NULL,\n    \"slot_key\" TEXT NOT NULL,\n    \"overrides\" JSONB NOT NULL,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"},
  {"type":"table","name":"story_versions","tableName":"story_versions","sql":"CREATE TABLE \"story_versions\" (\n    \"sealed_at\" DATETIME,\n    \"id\" TEXT NOT NULL PRIMARY KEY,\n    \"owner_id\" TEXT NOT NULL,\n    \"story_draft_id\" TEXT NOT NULL,\n    \"version_no\" INTEGER NOT NULL,\n    \"source_revision\" INTEGER NOT NULL,\n    \"title\" TEXT NOT NULL,\n    \"settings\" JSONB NOT NULL,\n    \"content_hash\" TEXT,\n    \"schema_version\" INTEGER NOT NULL DEFAULT 1,\n    \"created_at\" DATETIME NOT NULL\n)"}
] as const;
