'use client';
import {useState,useEffect} from 'react';
import {ArrowLeft,Check,Play,Save as SaveIcon,Users,BookOpen} from 'lucide-react';
import {applyCharacterTemplate,characterTemplateFromStory,type Story,type AssetRole} from '../../../packages/domain/src/story';
import type {Character} from './storage';
import {images} from '../lib/presentation/story-art';
import {ImageAssetPicker,useStoryArtwork} from './story-assets';
const sections=['基础信息','世界与开局','角色配置','画面与素材'];
export function Editor({initial,characters,onSave,onSaveCharacter,onBack,onPlay,notice,dialog}:{initial:Story;characters:Character[];onSave:(s:Story)=>boolean;onSaveCharacter:(c:Character)=>boolean;onBack:()=>void;onPlay:(s:Story)=>void;notice:string;dialog:React.ReactNode}){
 const [s,setS]=useState(initial),[section,setSection]=useState(0),[saved,setSaved]=useState(JSON.stringify(initial));
 const [busyRoles,setBusyRoles]=useState<Partial<Record<AssetRole,boolean>>>({}),[feedback,setFeedback]=useState('');
 const busy=Object.values(busyRoles).some(Boolean),dirty=JSON.stringify(s)!==saved,art=useStoryArtwork(s);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty||busy)e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty,busy]);
 function field(key:keyof Story,value:string){setS(prev=>({...prev,[key]:value}));}
 function save(){const ok=onSave(s);if(ok)setSaved(JSON.stringify(s));return ok;}
 function assetPicker(role:AssetRole){return <ImageAssetPicker role={role} assetId={s.assets?.[role]} onChange={id=>setS(prev=>({...prev,assets:{...prev.assets,[role]:id},...(role==='character'?{artId:undefined}:{})}))} onBusyChange={value=>setBusyRoles(prev=>({...prev,[role]:value}))}/>;}
 function saveCharacter(){if(!s.character.trim()||!s.personality.trim()){setFeedback('先填写角色姓名与性格背景，再保存为模板。');return;}if(onSaveCharacter(characterTemplateFromStory(s,crypto.randomUUID())))setFeedback('角色模板已保存。此剧本中的角色与模板独立编辑。');}
 return <div className="editor-shell">
  <header className="editor-header"><button disabled={busy} className="text-button" onClick={()=>{if(!dirty||confirm('还有未保存的修改，确定离开吗？'))onBack();}}><ArrowLeft size={18}/>我的剧本</button><span className="editor-title">{s.title||'未命名剧本'}<small>{busy?'正在保存图片…':dirty?'有未保存修改':'本地草稿'}</small></span><div><button disabled={busy} className="secondary" onClick={save}><SaveIcon size={16}/>保存草稿</button><button disabled={busy} className="primary" onClick={()=>{if(save())onPlay(s);}}><Play size={16}/>保存并进入准备</button></div></header>
  <div className="editor-layout"><aside className="editor-nav"><p className="eyebrow">STORY STUDIO</p><h2>构建你的开端</h2>{sections.map((x,i)=><button disabled={busy} className={section===i?'editor-tab active':'editor-tab'} key={x} onClick={()=>setSection(i)}><span>0{i+1}</span>{x}</button>)}<p className="editor-tip">不必写下所有情节。<br/>为角色和世界留一点空间，<br/>让故事在游玩中发生。</p></aside>
  <main className="editor-main"><p className="eyebrow">STEP 0{section+1} / 04</p><h1>{sections[section]}</h1><p className="muted">{['让玩家一眼知道，这是怎样一个故事。','定义起点，而不是替玩家决定终点。','先有一个鲜活的人，才会有想继续的故事。','封面给人看，参考图定义角色，开场图定义起点。'][section]}</p><div className="editor-fields">
  {section===0&&<><label>剧本名称 <span>*</span><input value={s.title} onChange={e=>field('title',e.target.value)} placeholder="为你的故事起一个名字" maxLength={60}/><small>一个令人想走进去的名字。</small></label><label>故事题材<select value={s.genre} onChange={e=>field('genre',e.target.value)}>{['浪漫','都市','奇幻','日常'].map(x=><option key={x}>{x}</option>)}</select></label><div className="inline-note"><BookOpen size={20}/><p>这是你的剧本，不是固定的剧情树。用户进入后可以用自己的对话和行动推动发展。</p></div></>}
  {section===1&&<><label>世界背景 <span>*</span><textarea value={s.world} onChange={e=>field('world',e.target.value)} placeholder="故事发生在哪里？这个世界有哪些规则？" rows={5}/></label><label>开局情境 <span>*</span><textarea value={s.opening} onChange={e=>field('opening',e.target.value)} placeholder="用几句话描述故事开始的这一刻…" rows={4}/><small>避免替玩家规定台词、行动和情感选择。</small></label></>}
  {section===2&&<>
   {characters.length>0&&<label>从角色库复制<select value="" disabled={busy} onChange={e=>{const c=characters.find(c=>c.id===e.target.value);if(c&&(!(s.character||s.personality||s.appearance||s.speakingStyle||s.boundaries||s.assets?.character||s.artId)||confirm('替换当前角色的姓名、设定与参考图？剧本背景和初始关系保持不变。')))setS(prev=>applyCharacterTemplate(prev,c));}}><option value="" disabled>选择角色模板</option>{characters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><small>完整复制外貌、表达习惯、边界与图片，后续独立编辑。</small></label>}
   <label>角色姓名 <span>*</span><input value={s.character} onChange={e=>field('character',e.target.value)} placeholder="TA 叫什么？" maxLength={60}/></label><label>性格与背景<textarea value={s.personality} onChange={e=>field('personality',e.target.value)} placeholder="TA 的性格、经历，以及想做什么…" rows={3}/></label><div className="character-fields-grid"><label>外貌与穿着<textarea value={s.appearance??''} onChange={e=>field('appearance',e.target.value)} placeholder="发型、神态、常穿的衣服…" rows={3}/></label><label>表达习惯<textarea value={s.speakingStyle??''} onChange={e=>field('speakingStyle',e.target.value)} placeholder="说话直接，还是慢慢表达？" rows={3}/></label></div><label>你们的初始关系<input value={s.relationship??''} onChange={e=>field('relationship',e.target.value)} placeholder="例如初次见面、熟识，或你自己的设定"/><small>关系属于这个剧本，不随角色模板复制。</small></label><label>相处边界<textarea value={s.boundaries??''} onChange={e=>field('boundaries',e.target.value)} placeholder="例如尊重距离，不替玩家表达感情…" rows={3}/></label>
   {assetPicker('character')}{s.artId&&!s.assets?.character&&<div className="inline-note"><p>此剧本带有演示角色视觉。选择自己的图片会替换它。</p><button type="button" className="text-button" onClick={()=>setS(prev=>({...prev,artId:undefined}))}>移除演示视觉</button></div>}
   <button type="button" className="secondary" disabled={busy} onClick={saveCharacter}><Users size={16}/>另存为角色模板</button><div className="inline-note"><Users size={20}/><p>一期支持一位主要角色。角色模板、剧本草稿与游玩设定独立，修改不会串到其他故事。</p></div>
  </>}
  {section===3&&<>{assetPicker('cover')}{assetPicker('opening')}<label>未选自定义图片时的封面</label><div className="image-options">{Object.entries(images).map(([key,url],i)=><button aria-pressed={s.image===key} className={s.image===key?'image-option picked':'image-option'} key={key} onClick={()=>field('image',key)}><img src={url} alt={['海边','夜空','森林','小屋'][i]}/><span>{['海边','夜空','森林','小屋'][i]}{s.image===key&&<Check size={14}/>}</span></button>)}</div><div className="inline-note"><p>图片现阶段只保存在本机，不代表已经交给视频模型。正式生成会按供应商与模型校验素材用途；封面不进入生成提示。</p></div></>}
  </div><div className="editor-bottom"><span>{section+1} / 4</span>{section<3?<button disabled={busy} className="primary" onClick={()=>setSection(section+1)}>继续配置 →</button>:<button disabled={busy} className="primary" onClick={save}>保存剧本<Check size={16}/></button>}</div>{feedback&&<p className="inline-note" role="status">{feedback}</p>}{notice&&<p className="inline-note" role="status">{notice}</p>}</main>
  <aside className="editor-preview"><p className="eyebrow">你的故事，初见模样</p><div className="preview-cover" style={{backgroundImage:art.url?`url(${art.url})`:undefined}}><span>{s.genre} · 开放故事</span><h2>{s.title||'一个尚未命名的故事'}</h2></div>{art.missing&&<p role="status">本机图片缺失，请重新选择。</p>}<h3>{s.character||'等待一位角色'}</h3><p>{s.world||'你的世界会在这里慢慢浮现。'}</p><hr/><small>这是封面预览，不是生成中的视频。<br/>图片选好即存本机，设定点击保存后生效。</small></aside>
  </div>{dialog}
 </div>;
}
