'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Bookmark,Plus,Pencil,Trash2,Check} from 'lucide-react';
import type {Save} from '../../../packages/domain/src/story';
import {pinMemory,editMemory,removeMemory} from '../../../packages/domain/src/story';
export function StoryJournal({save,onChange,onClose}:{save:Save;onChange:(s:Save)=>boolean;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);const [tab,setTab]=useState('memories'),[text,setText]=useState(''),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState('');
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 function close(){if(!text.trim()||confirm('还有未保存的记录，确定放弃并关闭吗？'))onClose();}
 function update(next:Save){if(onChange(next)){setError('');return true;}setError('保存失败，内容已保留。请检查本地存储。');return false;}
 return <dialog ref={ref} className="journal" onCancel={e=>{e.preventDefault();close();}} aria-labelledby="journal-title"><header><div><p className="eyebrow">THE THINGS WE KEEP</p><h2 id="journal-title">故事里的痕迹</h2></div><button aria-label="关闭记录" onClick={close} autoFocus><X size={21}/></button></header><div className="journal-tabs"><button aria-pressed={tab==='memories'} onClick={()=>setTab('memories')}>共同经历<span>{save.memories?.length??0}</span></button><button aria-pressed={tab==='actions'} onClick={()=>setTab('actions')}>行动记录<span>{save.turns.length}</span></button></div>{tab==='memories'?<><p className="journal-description">留住你觉得重要的时刻。由你确认，不自动推断关系；记录仅属于这次故事。</p><form className="memory-form" onSubmit={e=>{e.preventDefault();if(!text.trim())return;if(update(editing?editMemory(save,editing,text):pinMemory(save,text))){setText('');setEditing(null);}}}><label>{editing?'修正这段记录':'记下一件小事'}<textarea maxLength={1000} placeholder="一句约定，一个想记住的瞬间…" value={text} onChange={e=>setText(e.target.value)} rows={3}/></label><div>{editing&&<button type="button" onClick={()=>{setEditing(null);setText('');}}>取消编辑</button>}<button className="primary" disabled={!text.trim()}><Check size={14}/>{editing?'保存修改':'保存这段经历'}</button></div></form>{!save.memories?.length?<div className="journal-empty"><Bookmark size={26}/><h3>还没有被记下的时刻</h3><p>不必为了进度而收集。<br/>等某个瞬间对你有意义，再把它留下。</p></div>:save.memories.map(m=><article className="memory-card" key={m.id}><small>你确认的经历 · {new Date(m.createdAt).toLocaleDateString('zh-CN')}</small><p>{m.text}</p><footer><button aria-label={`编辑经历：${m.text}`} onClick={()=>{if(!text.trim()||confirm('替换当前未保存的记录？')){setEditing(m.id);setText(m.text);}}}><Pencil size={14}/>修正</button><button aria-label={`删除经历：${m.text}`} onClick={()=>{if(confirm('删除这段记录？行动历史不会被删除。')&&update(removeMemory(save,m.id))&&editing===m.id){setEditing(null);setText('');}}}><Trash2 size={14}/>删除</button></footer></article>)}</>:<><p className="journal-description">行动已记录不代表视频已应用。当前没有真实角色回应或画面生成。</p>{!save.turns.length?<div className="journal-empty"><h3>从你的第一句话开始</h3></div>:save.turns.map((t,i)=><article className="memory-card" key={t.id}><small>你的行动 {i+1} · 已记录（模拟）</small><p>{t.text}</p></article>)}</>}{error&&<p role="alert" className="error">{error}</p>}</dialog>
}
